### ISSUE TITLE
FHIR querying methods

### ISSUE THREAD

**Issue by shuchenliu** [sync-for-science/procure-wip#13]
Sorry if this is more of a question rather than an actual issue related to the `Procure` project.

We are developing an `FHIR`-based patient-facing app at Scripps and I noticed that `Procure` did not actually use any `FHIR` wrapper library available out there (like [`smart-on-fhir/client-js`](https://github.com/smart-on-fhir/client-js)). Rather, all the querying methods were implemented using `fetch` calls from scratch - I was just wondering if there was any special consideration behind this choice.

Thanks for your time and looking forward to your answer!

**Comment by gotdan** [comment]
@shuchenliu sorry for the delay in getting back to you - must have missed the notification for this issue :). 

When I started Procure, the SMART client library was structured around connecting to single FHIR endpoint per app by doing a full page redirect to authenticate, while I needed to connect to multiple FHIR endpoints and wanted to use a popup window for authentication. Given how embedded these assumptions were, it didn't make sense to update the existing library, so I wrote a small smart module for Procure.

Vlad subsequently rewrote the client library from scratch as client.js v2, and based on my input incorporating these options. However, since actual auth piece is a small part of Procure's codebase and is pretty stable, I left my custom implementation in place.
